## Sort, Search and Counting Function

In [1]:
import numpy as np

In [14]:
arr = np.random.randint(1,30, (10))

In [15]:
arr

array([ 2,  9, 12,  7,  9, 19,  1, 24, 26, 26])

## Sort() Function

`np.sort(a, axis=0)` The np.sort function sorts the input array a along thr specified axis, which is 0(columns) in this case. The result is stored in the variable 'x', which is an array with the same shape as a, but with the elements sorted along each column.

In [16]:
np.sort(arr)

array([ 1,  2,  7,  9,  9, 12, 19, 24, 26, 26])

In [17]:
arr1 = np.array([[1,3], [3,1], [4,5]])

In [18]:
np.sort(arr1)

array([[1, 3],
       [1, 3],
       [4, 5]])

In [21]:
np.sort(arr1, axis=0)

array([[1, 1],
       [3, 3],
       [4, 5]])

## searchsorted() Function

The searchsorted() function is used to find indices where elements should be inserted to maintain order.

Find the indices into a sorted Series self such that, if the corresponding elements in value were inserted before the indices, the order of self would be preserve

`Series.searchsorted(self, value, side='left', sorter=None)
`d.

In [22]:
np.searchsorted(arr, 10)

2

In [26]:
x = np.array(['tea', 'bread', 'butter', 'milk'])
x.searchsorted(['bread'], side='right')

array([2], dtype=int64)

## nonzero() Function

The np.count_nonzero() function is used to count the number of non-zero elements in the array ‘x’.

In [28]:
arr2 = np.array([0,0,1,2,100,32,28,0])

In [29]:
np.nonzero(arr2)

(array([2, 3, 4, 5, 6], dtype=int64),)

In [30]:
np.count_nonzero(arr2)

5

In [31]:
np.where(arr > 10)

(array([2, 5, 7, 8, 9], dtype=int64),)

In [32]:
np.extract(arr > 25, arr)

array([26, 26])

## Copies and Views

## Copy() function

The numpy.copy() function is used to get an array copy of an given object.

The copy() function can be useful when you want to make changes to an array without modifying the original array. For example, if you want to perform a series of operations on an array and keep the original array intact, you can create a copy of the original array using the copy() function and perform the operations on the copy. This can also be useful when you want to pass a copy of an array to a function without modifying the original array.

In [33]:
a = np.copy(arr)

In [34]:
a

array([ 2,  9, 12,  7,  9, 19,  1, 24, 26, 26])

## View Function

The view() function is used to create a new view of the Series.

This function returns a new Series with a view of the same underlying values in memory, optionally reinterpreted with a new data type. The new data type must preserve the same size in bytes as to not cause index misalignment.

In [35]:
b = arr.view()

In [36]:
b

array([ 2,  9, 12,  7,  9, 19,  1, 24, 26, 26])

In [37]:
b[1] = 65

In [38]:
b

array([ 2, 65, 12,  7,  9, 19,  1, 24, 26, 26])

In [39]:
arr

array([ 2, 65, 12,  7,  9, 19,  1, 24, 26, 26])

## Linear Algebra

In [48]:
arr1 = np.random.randint(1,30, (2,2))
arr2 = np.random.randint(1,30, (2,2))

In [49]:
arr1

array([[23, 20],
       [12, 19]])

In [50]:
arr2

array([[ 7, 17],
       [20,  9]])

In [51]:
np.dot(arr1, arr2)

array([[561, 571],
       [464, 375]])

In [52]:
arr1@arr2

array([[561, 571],
       [464, 375]])