In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,4))

In [5]:
arr

array([[8, 7, 2, 8],
       [8, 1, 5, 6],
       [4, 4, 8, 1]])

In [6]:
arr.reshape(2,5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [10]:
arr.reshape(2,6)

array([[8, 7, 2, 8, 8, 1],
       [5, 6, 4, 4, 8, 1]])

In [11]:
arr.T

array([[8, 8, 4],
       [7, 1, 4],
       [2, 5, 8],
       [8, 6, 1]])

In [12]:
arr.flatten()

array([8, 7, 2, 8, 8, 1, 5, 6, 4, 4, 8, 1])

In [13]:
arr1 = np.array([1,2,3,4,5,6])

In [15]:
arr1.ndim

1

In [16]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
arr

array([[8, 7, 2, 8],
       [8, 1, 5, 6],
       [4, 4, 8, 1]])

In [18]:
np.squeeze(arr)

array([[8, 7, 2, 8],
       [8, 1, 5, 6],
       [4, 4, 8, 1]])

In [19]:
data = np.array([[1], [2], [3]])

In [20]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
arr1

array([1, 2, 3, 4, 5, 6])

In [22]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [23]:
np.diag(arr1)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [24]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [25]:
arr1

array([[1, 2, 1, 4],
       [4, 4, 3, 3],
       [4, 9, 4, 3]])

In [26]:
arr2

array([[6, 5, 8, 4],
       [3, 7, 6, 9],
       [2, 7, 6, 2]])

In [27]:
arr1+arr2

array([[ 7,  7,  9,  8],
       [ 7, 11,  9, 12],
       [ 6, 16, 10,  5]])

In [28]:
arr1-arr2

array([[-5, -3, -7,  0],
       [ 1, -3, -3, -6],
       [ 2,  2, -2,  1]])

In [29]:
arr1*arr2

array([[ 6, 10,  8, 16],
       [12, 28, 18, 27],
       [ 8, 63, 24,  6]])

In [30]:
arr1**arr2

array([[      1,      32,       1,     256],
       [     64,   16384,     729,   19683],
       [     16, 4782969,    4096,       9]])

In [31]:
arr1 & arr2

array([[0, 0, 0, 4],
       [0, 4, 2, 1],
       [0, 1, 4, 2]])

In [32]:
arr1>arr2

array([[False, False, False, False],
       [ True, False, False, False],
       [ True,  True, False,  True]])

In [33]:
arr = np.array(["Abhishek", "Singh"])

In [34]:
arr

array(['Abhishek', 'Singh'], dtype='<U8')

In [35]:
np.char.upper(arr)

array(['ABHISHEK', 'SINGH'], dtype='<U8')

In [36]:
np.char.title(arr)

array(['Abhishek', 'Singh'], dtype='<U8')

In [37]:
arr1

array([[1, 2, 1, 4],
       [4, 4, 3, 3],
       [4, 9, 4, 3]])

In [38]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743,  0.84147098, -0.7568025 ],
       [-0.7568025 , -0.7568025 ,  0.14112001,  0.14112001],
       [-0.7568025 ,  0.41211849, -0.7568025 ,  0.14112001]])

In [39]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684,  0.54030231, -0.65364362],
       [-0.65364362, -0.65364362, -0.9899925 , -0.9899925 ],
       [-0.65364362, -0.91113026, -0.65364362, -0.9899925 ]])

In [40]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.71828183e+00, 5.45981500e+01],
       [5.45981500e+01, 5.45981500e+01, 2.00855369e+01, 2.00855369e+01],
       [5.45981500e+01, 8.10308393e+03, 5.45981500e+01, 2.00855369e+01]])

In [41]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        , 2.        ],
       [2.        , 2.        , 1.73205081, 1.73205081],
       [2.        , 3.        , 2.        , 1.73205081]])

In [42]:
np.power(arr1, 2)

array([[ 1,  4,  1, 16],
       [16, 16,  9,  9],
       [16, 81, 16,  9]], dtype=int32)

In [43]:
np.mean(arr1)

3.5

In [44]:
np.median(arr1)

3.5

In [45]:
np.std(arr1)

1.9790570145063195