In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[8, 2, 8, 9],
       [8, 7, 5, 4],
       [9, 7, 6, 8]])

In [4]:
arr.reshape(2,5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [5]:
arr.reshape(2,6)

array([[8, 2, 8, 9, 8, 7],
       [5, 4, 9, 7, 6, 8]])

In [6]:
arr.T

array([[8, 8, 9],
       [2, 7, 7],
       [8, 5, 6],
       [9, 4, 8]])

In [7]:
arr.flatten()

array([8, 2, 8, 9, 8, 7, 5, 4, 9, 7, 6, 8])

In [8]:
arr1 = np.array([1,2,3,4,5,6])

In [9]:
arr1.ndim

1

In [10]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
arr

array([[8, 2, 8, 9],
       [8, 7, 5, 4],
       [9, 7, 6, 8]])

In [12]:
np.squeeze(arr)

array([[8, 2, 8, 9],
       [8, 7, 5, 4],
       [9, 7, 6, 8]])

In [13]:
data = np.array([[1], [2], [3]])

In [14]:
np.squeeze(data)

array([1, 2, 3])

In [15]:
arr1

array([1, 2, 3, 4, 5, 6])

In [16]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [17]:
np.diag(arr1)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [18]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [19]:
arr1

array([[4, 2, 5, 3],
       [7, 6, 6, 9],
       [8, 4, 6, 8]])

In [20]:
arr2

array([[1, 4, 9, 2],
       [2, 5, 9, 4],
       [9, 4, 9, 5]])

In [21]:
arr1+arr2

array([[ 5,  6, 14,  5],
       [ 9, 11, 15, 13],
       [17,  8, 15, 13]])

In [22]:
arr1-arr2

array([[ 3, -2, -4,  1],
       [ 5,  1, -3,  5],
       [-1,  0, -3,  3]])

In [23]:
arr1*arr2

array([[ 4,  8, 45,  6],
       [14, 30, 54, 36],
       [72, 16, 54, 40]])

In [24]:
arr1**arr2

array([[        4,        16,   1953125,         9],
       [       49,      7776,  10077696,      6561],
       [134217728,       256,  10077696,     32768]])

In [25]:
arr1 & arr2

array([[0, 0, 1, 2],
       [2, 4, 0, 0],
       [8, 4, 0, 0]])

In [26]:
arr1>arr2

array([[ True, False, False,  True],
       [ True,  True, False,  True],
       [False, False, False,  True]])

In [27]:
arr = np.array(["Abhishek", "Singh"])

In [28]:
arr

array(['Abhishek', 'Singh'], dtype='<U8')

In [29]:
np.char.upper(arr)

array(['ABHISHEK', 'SINGH'], dtype='<U8')

In [30]:
np.char.title(arr)

array(['Abhishek', 'Singh'], dtype='<U8')

In [31]:
arr1

array([[4, 2, 5, 3],
       [7, 6, 6, 9],
       [8, 4, 6, 8]])

In [32]:
np.sin(arr1)

array([[-0.7568025 ,  0.90929743, -0.95892427,  0.14112001],
       [ 0.6569866 , -0.2794155 , -0.2794155 ,  0.41211849],
       [ 0.98935825, -0.7568025 , -0.2794155 ,  0.98935825]])

In [33]:
np.cos(arr1)

array([[-0.65364362, -0.41614684,  0.28366219, -0.9899925 ],
       [ 0.75390225,  0.96017029,  0.96017029, -0.91113026],
       [-0.14550003, -0.65364362,  0.96017029, -0.14550003]])

In [34]:
np.exp(arr1)

array([[5.45981500e+01, 7.38905610e+00, 1.48413159e+02, 2.00855369e+01],
       [1.09663316e+03, 4.03428793e+02, 4.03428793e+02, 8.10308393e+03],
       [2.98095799e+03, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03]])

In [35]:
np.sqrt(arr1)

array([[2.        , 1.41421356, 2.23606798, 1.73205081],
       [2.64575131, 2.44948974, 2.44948974, 3.        ],
       [2.82842712, 2.        , 2.44948974, 2.82842712]])

In [36]:
np.power(arr1, 2)

array([[16,  4, 25,  9],
       [49, 36, 36, 81],
       [64, 16, 36, 64]], dtype=int32)

In [37]:
np.mean(arr1)

5.666666666666667

In [38]:
np.median(arr1)

6.0

In [39]:
np.std(arr1)

2.0548046676563256